workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
      - name: Install Flutter dependencies
        script: |
          cd hellotest
          flutter pub get
      - name: Clean derived data
        script: rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Clean Flutter cache
        script: flutter clean
      - name: Set architecture for simulator builds
        script: |
          export ARCHS="x86_64 arm64"
          export ONLY_ACTIVE_ARCH=NO
      - name: Build for simulator
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=latest' \
            -configuration Release \
            -allowProvisioningUpdates

      - name: Build for devices
        script: |
          xcodebuild archive -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -allowProvisioningUpdates
