workflows:
  ios_build:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      CODE_SIGNING_IDENTITY: "iPhone Developer"
      CODE_SIGNING_IDENTITY_DEVELOPMENT: "iPhone Developer"
      CODE_SIGNING_IDENTITY_AD_HOC: "iPhone Distribution"
      PROVISIONING_PROFILE_DEVELOPMENT: "YOUR_DEVELOPMENT_PROFILE"
      PROVISIONING_PROFILE_AD_HOC: "YOUR_AD_HOC_PROFILE"
    scripts:
      - xcodebuild clean build -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release -destination 'generic/platform=iOS Simulator,name=iPhone 14 Pro Max' -arch arm64
      - xcodebuild archive -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release -destination 'generic/platform=iOS Simulator,name=iPhone 14 Pro Max' -arch x86_64
      - xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release -destination generic/platform=iOS -archivePath YourArchive.xcarchive