
workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
      - name: Install Flutter dependencies
        script: |
          cd hellotest
          flutter pub get
      - name: Clear Derived Data and Cache
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Flutter/Flutter.framework
          flutter clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set architecture for builds
        script: |
          export ARCHS="x86_64 arm64"
          export ONLY_ACTIVE_ARCH=NO
      - name: Build for simulator
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            ONLY_ACTIVE_ARCH=NO \
            -UseModernBuildSystem=NO
      - name: Build for devices
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Development" \
            ONLY_ACTIVE_ARCH=NO
