ios:
  build:
    scheme: "Runner"
    export_method: "development"
    simulator: true 
  scripts:
    - name: Set architecture for simulator builds
        script: |
          export ARCHS="x86_64 arm64"
          export ONLY_ACTIVE_ARCH=NO 